name: kinasepki
dependencies:
- conda-forge::python=2.7
- conda-forge::numpy>=1.16.5
- conda-forge::h5py>=2.7.0
- conda-forge::pandas>=0.24.2
- conda-forge::scikit-learn>=0.20.4
- conda-forge::tensorflow>=1.13.2
- conda-forge::keras>=2.3.1
- anaconda::docopt>=0.6.2
- rdkit::rdkit>=2018.03
- pip:
  - pydpi==1.0
  - xgboost
  - matplotlib